# tuple of (min, max) total energy to consider per event.
# if None (default), no cut is applied  
energy_range: [1, 200]

# minimum number of channels to consider per event 
min_ch: 1

# minimum energy per channel to consider per event
en_min_ch: 0

# path to map file
map_file: maps/erc_map.yaml