# tuple of (min, max) total energy to consider per event.
# if None (default), no cut is applied  
energy_range: [0, 1500]

# minimum number of channels to consider per event 
min_ch: 4

# minimum energy per channel to consider per event
en_min_ch: 0.2

# path to map file
map_file: maps/imas_map.yaml